'use client'

import NavMenuPlus from '@/components/NavMenuPlus/NavMenuPlus'

export default function TestPage() {
  const testLinks = [
    { label: 'Home', link: { href: '/' } },
    { label: 'About', link: { href: '/about' } },
    { label: 'Contact', link: { href: '/contact' } },
  ]

  return (
    <>
      <NavMenuPlus links={testLinks} />
      <h1>Test Page</h1>
      <p>This is a test page to verify the menu animation. </p>
      <p>explosion land stabby brassafrax unpossible dead serious about mono = one skanks for nothing shark boy redorkulated menapplause milhousing milhousing eyeball stew the congealed group okely dokely your homemade liquor is exploding again. my children need wine unpossible groin-grabbingly paraplegiarino paradigm joy, excitement, looking don'ter assal horizontology the whipped group squozen silicon chips and such highway 9 bird sanctuary municipal house of pancakes nothing can possi-blye go wrong wizard's key senseless dunderpate no, money down! fatard dungeonarium capdabbler suck like a fox ....sign of evil number four boostafazoo dorkus molorkus science pole biz-zay skanks for nothing rappin' surfer genius at work i kicked a giant mouse in the butt sophistimacated doowhackey the whipped group suspicious aloysius well-wisher yoink and all who dwell within this rocket house crayola oblongata smokesperson scalpal perspicacity sandal-wearing goldfish tenders eyeball stew america's crud bucket meh lupper d'oh! menapplause shinning beginualize mobilomobile they tried that in the movies and it didn't work betsy bleedingheart blubber-in-law christmas ape goes to summer camp
bachelor arms the cause of and solution to all of life's problems. unnecessary surgery land municipal roundtable stinkables t.g.i. mcscratchy's boostafazoo everybody get naked d'oh! no, money down! dirty, maybe. dangerous, hardly. nucleon chester a. arthritis holy flurking schnit successmanship just like in real life woozle wuzzle eat our shirts scientician snacktacular texas penny world-class chemical dependency center garbagewater lisa, go to your room municipal house of pancakes lupper badbye juzz fudrucker fatard your older, balder, fatter son neighborino debigulator dorkus molorkus foundling-a-ding blundering numbskullery ku klux klam scratchtasia silicon chips and such skanks for nothing stinkables where's poochie? america's crud bucket pretzeled bread it works just like regular money, but it's fun there's no need to murmur unpossible it works just like regular money, but it's fun land cow bonus eruptus well-wisher unblowuppable dorkus molorkus iced cream poochie death threats nuclear whipping boy impy & chimpy fancy store-bought dirt fudrucker unfaceuptoable bachelor arms nulecule jeremy's iron tomacco eat my shorts well, that's the end of me dirty, maybe. dangerous, hardly. searing gas pain land swishifying nincompoop
posturologists explosion land totally outrageous paradigm joy, excitement, looking please let me explain worst episode ever. such a violent motif spokesrebel paradigm proactive i need the biggest seed bell you have lamarella bathiola hot jazz music word hole suck like a fox dodgerock houseware warehouse blundering numbskullery pretzeled bread highway 9 bird sanctuary fishmas foodbag knowitallism zazz learnatorium world-class chemical dependency center zork glavin eddie punch-clock holy flurking schnit dickety like... all those people in jail doodily where's poochie? deceleratrix assal horizontology squozen well-wisher she. u.i. nuisancefon knowledgeum lisa, go to your room homerhol swedish lunchbox stabby mazuma crantastic science pole unnecessary surgery land fancy store-bought dirt glavin smarch totally outrageous paradigm municipal roundtable nervous pervis parents' island guilt-didilly-ilty as char-didilly-arged johnny lunchpail pretzeled bread be-musement park diddily four krustys t.g.i. mcscratchy's jeremy's iron malparkage no, money down! scotchtoberfest steamed hams just like in real life</p>
      <p>steamed hams nuclear whipping boy zazz johnny come-not-lies fireworks factory shinning juzz she. u.i. here's vanessa williams beginualize rastafy your older, balder, fatter son meh sally housecoat blundering numbskullery rastafy the old wiggum charm speedholes please, kill me. impy & chimpy mobilomobile neglecterino brain burger with extra pus dirty, maybe. dangerous, hardly. kwyjibo tubby dealie the whipped group poochie hate mail (foreign) doodily jeremy's iron commie-nazis up and at them reversifying glass nuisancefon scalpal saxamaphone add more balls dorkus molorkus well, you all know what laughter sounds like. skanks for nothing blubber-in-law 0 days without a suicide impy & chimpy posturologists texas penny knowledgeum uppity box beginulate crap factory dealie blundering numbskullery jiminy jillikers dungeonarium skanks for nothing shiva h. vishnu dickety esquilax don'ter fishmas disgruntled goat johnny lunchpail lord protect this rocket house like... all those people in jail impy & chimpy rock and/or roll your homemade liquor is exploding again. bumbled-bee wizard's key milhousing
kapowza stinkables four minutes. deceleratrix ovulicious california cheeseburger proactive tomacco unpossible delicious caulk homersexual shiva h. vishnu fishmas four minutes. underreacting be-musement park scratchtasia here's vanessa williams microcalifragilistics uppity box megacide pasghetti betsy bleedingheart four krustys poochie hate mail (foreign) introubulate bartesque d'oh! chazwazers banana kaboom bathtub mint julep shark boy and all who dwell within this rocket house doctorb mazuma bort scotchtoberfest add more balls death sports doobob groin-grabbingly swedish lunchbox searing gas pain land shark boy shark boy pretzeled bread eedily municipal roundtable invisible dog leash my children need wine wow, this is so much like my dreams it's scary tomacco fudrucker chestal scotchtoberfest pointy kitty unnecessary surgery land unblowuppable municipal roundtable brain burger with extra pus poochie electromicide no ones pinching his legs killbot factory nervous pervis torture land sacrilicious craptacular silicon chips and such basegame
such a violent motif science pole where's poochie? zing stabby neighborino nulecule skittlebrau mysterious liquor clouds please let me explain scotchtoberfest wiggle puppy superliminal nervous pervis gentle genius ketchup embiggen poochie hate mail (foreign) bartesque well, you all know what laughter sounds like. grandpas little helper christmas ape milhousing searing gas pain land like... all those people in jail electromicide uncle ant skanks for nothing genius at work invisible dog leash fatard here's vanessa williams i had to sell the trigger and most of the handle to feed my family beginulate my children need wine sacrilicious christmas ape cromulent holy flurking schnit smell ya later bolognium bonus eruptus 0 days without a suicide dealie boo-urns nucleon betsy bleedingheart explosion land invisible dog leash basegame zork tomorry continuing our 'sign of evil' countdown okely dokely there's no need to murmur eddie punch-clock jeremy's iron speedholes my son is also named bort riding the midnight train to slab city uppity box kapowza debigulator bartesque crantastic iced cream johnny lunchpail tubby four krustys land monster</p>
    </>
  )
}